---
name: Hello World!

on:
  push:
    branches:
      - main

jobs:
  hello_world_job:
    runs-on: ubuntu-20.04
    steps:
      - name: Say hello
        run: |
          echo "Hello World!"

  print_date_and_dir:
    runs-on: ubuntu-20.04
    steps:
      - name: Print date
        run: |
          date
      - name: List directory
        run: |
          ls -l
...